apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: LoadBalancer
  ports:
    - ports: 80
      targetPod: 80
  selector:
    withLabels:
      name: result-app-pod
      app: demo-voting-app